//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ovis
{
    [Serializable]
    public class HomeJointRequest : Message
    {
        public const string k_RosMessageName = "ovis_msgs/HomeJoint";
        public override string RosMessageName => k_RosMessageName;


        public HomeJointRequest()
        {
        }
        public static HomeJointRequest Deserialize(MessageDeserializer deserializer) => new HomeJointRequest(deserializer);

        private HomeJointRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "HomeJointRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
