//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ovis
{
    [Serializable]
    public class OvisIKGoalMsg : Message
    {
        public const string k_RosMessageName = "ovis_msgs/OvisIKGoal";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg target;

        public OvisIKGoalMsg()
        {
            this.target = new Geometry.PoseMsg();
        }

        public OvisIKGoalMsg(Geometry.PoseMsg target)
        {
            this.target = target;
        }

        public static OvisIKGoalMsg Deserialize(MessageDeserializer deserializer) => new OvisIKGoalMsg(deserializer);

        private OvisIKGoalMsg(MessageDeserializer deserializer)
        {
            this.target = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
        }

        public override string ToString()
        {
            return "OvisIKGoalMsg: " +
            "\ntarget: " + target.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
